"""empty message

Revision ID: 226965e264bf
Revises: 60cbb5ba2ff1
Create Date: 2023-08-16 17:09:06.969977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226965e264bf'
down_revision = '60cbb5ba2ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
