"""Added token_expiry_date and other fields

Revision ID: 7ac8b4b89320
Revises: 13d7882f67d0
Create Date: 2023-08-15 07:37:07.767320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac8b4b89320'
down_revision = '13d7882f67d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiry_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiry_date')

    # ### end Alembic commands ###
