"""empty message

Revision ID: 87da3390d1f6
Revises: 
Create Date: 2023-07-25 09:35:55.295478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87da3390d1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tokens')

    # ### end Alembic commands ###
