"""Added ActivityLog

Revision ID: 980b04b9552c
Revises: 7ac8b4b89320
Create Date: 2023-08-15 11:54:46.450882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980b04b9552c'
down_revision = '7ac8b4b89320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_log')
    # ### end Alembic commands ###
